---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: random-team-generator
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: app
        image: registry.gitlab.com/koen.konst/random-teams-generator/backend:1-2
        resources: {}
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgres.random-team-generator:5432/rtg?currentSchema=rtg"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "rtg_user"
          - name: SPRING_DATASOURCE_USERNAME
            value: "rtg_user"
---
