---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: random-team-generator
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: app
        image: registry.gitlab.com/koen.konst/random-teams-generator/backend:1-1
        resources: {}
      - env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgres.random-team-generator:5432/rtg?currentSchema=rtg"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "rtg_user"
          - name: SPRING_DATASOURCE_USERNAME
            value: "rtg_user"
---
