apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: random-team-generator
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: frontend
            port: 
              name: http
        path: /
        pathType: Prefix
