---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: random-team-generator
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: random-team-generator
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: app
        image: registry.gitlab.com/koen.konst/random-teams-generator/frontend:fix-frontend-auth
        ports:
          - name: http
            containerPort: 8080
---
